# The AWS::Serverless transform, which is a macro hosted by AWS CloudFormation, takes an entire template written in the AWS Serverless Application Model (AWS SAM) syntax and transforms and expands it into a compliant AWS CloudFormation template.
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
Transform: AWS::Serverless-2016-10-31

# Globals is a section in your SAM template to define properties common to all your Serverless Function and APIs. All the AWS::Serverless::Function and AWS::Serverless::Api resources will inherit the properties defined here.
Globals:
  Function:
    Runtime: nodejs10.x
    Handler: index.default # export handler function as default from index.js file
    Timeout: 30
    Environment:
      Variables:
        MyBunningsTable: !Ref MyBunningsTableV2
    # user default here?


Resources:
  FetchProducts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .aws-sam/build/fetchProducts
      Events:
        Api: # API name
          Type: Api
          Properties:
            Path: /products
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyBunningsTableV2
  GetSpecials:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .aws-sam/build/getSpecials
      Events:
        Api: # API name
          Type: Api
          Properties:
            Path: /specials
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyBunningsTableV2

  MyBunningsTableV2:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: entityType
          AttributeType: S
        - AttributeName: entityId
          AttributeType: S
        - AttributeName: priceChange
          AttributeType: N
      KeySchema:
        - AttributeName: entityId
          KeyType: HASH
        - AttributeName: entityType
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: PriceChangeIndexV2
          KeySchema:
            - AttributeName: entityType
              KeyType: HASH
            - AttributeName: priceChange
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes: [price, timestamp, displayName, productUrl, productImage]
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
