# The AWS::Serverless transform, which is a macro hosted by AWS CloudFormation, takes an entire template written in the AWS Serverless Application Model (AWS SAM) syntax and transforms and expands it into a compliant AWS CloudFormation template.
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
Transform: AWS::Serverless-2016-10-31

# Globals is a section in your SAM template to define properties common to all your Serverless Function and APIs. All the AWS::Serverless::Function and AWS::Serverless::Api resources will inherit the properties defined here.
Globals:
  Function:
    Runtime: nodejs12.x
    Handler: index.default # export handler function as default from index.js file
    Timeout: 30
    # Environment:
      # Variables:
    # user default here?


Resources:
  SearchProducts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .aws-sam/build/searchProducts
      Events:
        Api: # API name
          Type: Api
          Properties:
            Path: /products
            Method: GET

  